baseurl = "https://www.danielwatts.info"
languageCode = "en"
title = "Daniel Watts"
theme = "hucore"
copyright = ""
disqusShortname = ""
googleAnalytics = "UA-40668336-1"
paginate = 5

[params]
author = "Daniel Watts"
description = "An engineering leader and CTO with a focus on building high-performing teams and helping them create high-quality, maintainable products."
keywords = [ "engineering", "leadership", "CTO", "technology", "software", "engineer" ]

[taxonomies]
tag = "tags"
category = "categories"

[params.highlight]
style = "github"
languages = []

[[params.social]]
url = "https://www.linkedin.com/in/danielwatts2/"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://github.com/danbadge"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/dan_badge"
fa_icon = "fa-twitter"
