baseurl = "https://www.danielwatts.info"
languageCode = "en"
title = "Daniel Watts"
theme = "hemingway2"
copyright = ""
disqusShortname = ""
googleAnalytics = ""
description = "Stuff I did in teams building software"
keywords = []

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = []

[[params.social]]
url = "https://github.com/danbadge"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/dan_badge"
fa_icon = "fa-twitter"
